"""

the main line 'PYTHONPATH=tushar_portfolio waitress-serve --port=$PORT tushar_portfolio.wsgi:application'
Django settings for tushar_portfolio project.
Generated by 'django-admin startproject' using Django 5.2.4.
"""
 # Load environment variables from .env file

print("THIS IS MY SETTINGS.PY folder ")
import os

from pathlib import Path
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
print("THIS IS MY SETTINGS.PY and error comes after this line")


DEBUG = os.getenv("DEBUG", "False") == "True"
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

print("THIS IS MY SETTINGS.PY secret key 00")
SECRET_KEY = "9d0@1x0yc7m00$=%48f-6beb772c5tq+3aq&odh9@*+nnn^@bq"
print("THIS IS MY SETTINGS.PY secret_key", SECRET_KEY)


print("THIS IS MY SETTINGS.PY allowed hosts 00")

ALLOWED_HOSTS = ['127.0.0.1', 'localhost','tushar-portfolio-1.onrender.com']
print("THIS IS MY SETTINGS.PY allowed hosts 01", ALLOWED_HOSTS)
# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Your apps
    'home',
    'projects',
    'resume',
    'contact',
]
CSRF_TRUSTED_ORIGINS = [
    'https://tushar-portfolio-1.onrender.com',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For serving static files in prod
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tushar_portfolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
print("THIS IS MY SETTINGS.PY wsgi application 00")
WSGI_APPLICATION = 'tushar_portfolio.wsgi.application'
print("THIS IS MY SETTINGS.PY wsgi application 01", WSGI_APPLICATION)

# Database
# Default is SQLite; change ENGINE + other values for PostgreSQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

import os
from pathlib import Path

# Project base directory
BASE_DIR = Path(__file__).resolve().parent.parent

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

# Path where collectstatic will gather all static files
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Additional locations of static files (e.g., in your app's 'static/' folder)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# For WhiteNoise (use this only in production)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Media files (if you have any uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email settings (for contact form or feedback)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST='smtp.gmail.com'
EMAIL_PORT='587'
EMAIL_HOST_USER='jangratushar348@gmail.com'
EMAIL_HOST_PASSWORD='xbay pqvn puve kbiw'
EMAIL_USE_TLS='True'

print("everthing is fine in settings.py") 

GEMINI_API_KEY='AIzaSyD5QuAAmVq-Dt-LF06bV_8cK1GIJj7d2-M'



  
  