services:
  - type: web
    name: tushar-portfolio
    env: python
    buildCommand: ""
    startCommand: waitress-serve --port=$PORT tushar_portfolio.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: django-insecure-zsr8spkncp87*!@s*nduuyul+i4x5c8cqbwa4ovw!^!v@0%m#a
      - key: ALLOWED_HOSTS
      
        value: ['127.0.0.1', 'localhost']

